#!/usr/bin/python3.8
import os
import helpers

UNIT3D_VERSION = "2.1"

# Where the script is running from
try:
    SCRIPT_PATH = os.path.dirname(os.path.realpath(__file__))
except:
    SCRIPT_PATH = os.getcwd()

if helpers.is_windows():
    CONFIG_PATH = f"{os.environ.get('USERPROFILE')}/.BLU_Auto.ini"
else:
    CONFIG_PATH = f"{os.environ.get('HOME')}/.BLU_Auto.ini"

TMDB_API_KEY = "aa8b43b8cbce9d1689bef3d0c3087e4d"

# Default Values
IMAGE_WIDTH = 300
MAX_WAIT = 3

# Category ID's
MOVIE_CATEGORY_ID = "1"
TV_CATEGORY_ID = "2"
FANRES_CATEGORY_ID = "3"
CATEGORIES = {
    MOVIE_CATEGORY_ID: "Movie",
    "Movie": MOVIE_CATEGORY_ID,
    TV_CATEGORY_ID: "TV",
    "TV": TV_CATEGORY_ID,
    FANRES_CATEGORY_ID: "Fanres",
    "Fanres": FANRES_CATEGORY_ID,
}

# Type ID's
FULL_DISC_TYPE_ID = "1"
REMUX_TYPE_ID = "3"
ENCODE_TYPE_ID = "12"
WEBDL_TYPE_ID = "4"
WEBRIP_TYPE_ID = "5"
HDTV_TYPE_ID = "6"
TYPES = {
    FULL_DISC_TYPE_ID: "Full Disc",
    "Full Disc": FULL_DISC_TYPE_ID,
    REMUX_TYPE_ID: "Remux",
    "Remux": REMUX_TYPE_ID,
    ENCODE_TYPE_ID: "Encode",
    "Encode": ENCODE_TYPE_ID,
    WEBDL_TYPE_ID: "WEB-DL",
    "WEB-DL": WEBDL_TYPE_ID,
    WEBRIP_TYPE_ID: "WEBRip",
    "WEBRip": WEBRIP_TYPE_ID,
    HDTV_TYPE_ID: "HDTV",
    "HDTV": HDTV_TYPE_ID,
}

# Resolution ID's
RESOLUTION_ID_8640p = "10"
RESOLUTION_ID_4320p = "11"
RESOLUTION_ID_2160p = "1"
RESOLUTION_ID_1080p = "2"
RESOLUTION_ID_1080i = "3"
RESOLUTION_ID_720p = "5"
RESOLUTION_ID_576p = "6"
RESOLUTION_ID_576i = "7"
RESOLUTION_ID_480p = "8"
RESOLUTION_ID_480i = "9"
RESOLUTION_ID_OTHER = "10"
# Allow for both way decoding
RESOLUTIONS = {
    RESOLUTION_ID_8640p: "8640p",
    "8640p": RESOLUTION_ID_8640p,
    RESOLUTION_ID_4320p: "4320p",
    "4320p": RESOLUTION_ID_4320p,
    RESOLUTION_ID_2160p: "2160p",
    "2160p": RESOLUTION_ID_2160p,
    RESOLUTION_ID_1080p: "1080p",
    "1080p": RESOLUTION_ID_1080p,
    RESOLUTION_ID_1080i: "1080i",
    "1080i": RESOLUTION_ID_1080i,
    RESOLUTION_ID_720p: "720p",
    "720p": RESOLUTION_ID_720p,
    RESOLUTION_ID_576p: "576p",
    "576p": RESOLUTION_ID_576p,
    RESOLUTION_ID_576i: "576i",
    "576i": RESOLUTION_ID_576i,
    RESOLUTION_ID_480p: "480p",
    "480p": RESOLUTION_ID_480p,
    RESOLUTION_ID_480i: "480i",
    "480i": RESOLUTION_ID_480i,
    RESOLUTION_ID_OTHER: "Other",
    "Other": RESOLUTION_ID_OTHER,
}

# Groups that guessit detects, but are not actual groups.
EXCLUDED_GROUPS = ["Hybrid"]

# Banned groups on BLU, two categories all and non-raw
BANNED_ALL = [
    "AROMA",
    "aXXo",
    "BRrip",
    "CM8",
    "CrEwSaDe",
    "d3g",
    "DNL",
    "FGT",
    "FaNGDiNG0",
    "FRDS",
    "HD2DVD",
    "HDTime",
    "iPlanet",
    "KiNGDOM",
    "Leffe",
    "MeGusta",
    "mHD",
    "mSD",
    "nHD",
    "nikt0",
    "nSD",
    "NhaNc3",
    "PRODJi",
    "RDN",
    "SANTi",
    "STUTTERSHIT",
    "ViSION",
    "WAF",
    "x0r",
    "YIFY",
]
BANNED_ALLOWED_RAW = ["CMRG", "EVO", "TERMiNAL"]

# Streaming Networks.
NETWORK = {
    "A&E": "AE",
    "ABC": "AMBC",
    "ABC Australia": "AUBC",
    "Adult Swim": "AS",
    "Al Jazeera English": "AJAZ",
    "Amazon Prime": "AMZN",
    "AMC": "AMC",
    "America's Test Kitchen": "ATK",
    "Animal Planet": "ANPL",
    "AnimeLab": "ANLB",
    "AOL": "AOL",
    "AppleTV": "ATVP",
    "ARD": "ARD",
    "BBC iPlayer": "iP",
    "BravoTV": "BRAV",
    "Canal+": "CNLP",
    "Cartoon Network": "CN",
    "CBC": "CBC",
    "CBS": "CBS",
    "Channel 4": "4OD",
    "CHRGD": "CHGD",
    "Cinemax": "CMAX",
    "CNBC": "CNBC",
    "Comedians in Cars Getting Coffee": "CCGC",
    "Comedy Central": "CC",
    "Country Music Television": "CMT",
    "Crackle": "CRKL",
    "Crunchy Roll": "CR",
    "CSpan": "CSPN",
    "CTV": "CTV",
    "CuriosityStream": "CUR",
    "CWSeed": "CWS",
    "Daisuki": "DSKI",
    "DC Universe": "DCU",
    "Deadhouse Films": "DHF",
    "Digiturk Diledigin Yerde": "DDY",
    "Discovery": "DISC",
    "Disney": "DSNY",
    "Disney Plus": "DSNP",
    "DIY Network": "DIY",
    "Doc Club": "DOCC",
    "DPlay": "DPLY",
    "DramaFever": "DF",
    "E!": "ETV",
    "El Trece": "ETTV",
    "ePix": "EPIX",
    "ESPN": "ESPN",
    "Esquire": "ESQ",
    "Family": "FAM",
    "Family Jr": "FJR",
    "Food Network": "FOOD",
    "Fox": "FOX",
    "Freeform": "FREE",
    "Funimation": "FM",
    "FYI Network": "FYI",
    "Global": "GLBL",
    "GloboSat Play": "GLOB",
    "Hallmark": "HLMK",
    "HBO Go": "HBO",
    "HBO Max": "HMAX",
    "HGTV": "HGTV",
    "History": "HIST",
    "Hulu": "HULU",
    "IFC": "IFC",
    "Investigation Discovery": "ID",
    "iTunes": "iT",
    "ITV": "ITV",
    "Knowledge Network": "KNOW",
    "Lifetime": "LIFE",
    "MBC": "MBC",
    "Motor Trend OnDemand": "MTOD",
    "MSNBC": "MNBC",
    "MTV": "MTV",
    "National Geographic": "NATG",
    "NBA TV": "NBA",
    "NBC": "NBC",
    "Netflix": "NF",
    "NFL": "NFL",
    "NFL Now": "NFLN",
    "NHL GameCenter": "GC",
    "Nickelodeon": "NICK",
    "Norsk Rikskringkasting": "NRK",
    "OnDemandKorea": "ODK",
    "Paramount+": "PMTP",
    "PBS": "PBS",
    "PBS Kids": "PBSK",
    "Playstation Network": "PSN",
    "Pluzz": "PLUZ",
    "RTE One": "RTE",
    "SBS (AU)": "SBS",
    "SeeSo": "SESO",
    "Shomi": "SHMI",
    "Showtime": "SHO",
    "Spike": "SPIK",
    "Spike TV": "SPKE",
    "Sportsnet": "SNET",
    "Sprout": "SPRT",
    "Stan": "STAN",
    "Starz": "STZ",
    "Sveriges Television": "SVT",
    "SwearNet": "SWER",
    "Syfy": "SYFY",
    "TBS": "TBS",
    "TFou": "TFOU",
    "The CW": "CW",
    "TLC": "TLC",
    "TubiTV": "TUBI",
    "TV3 Ireland": "TV3",
    "TV4 Sweeden": "TV4",
    "TVING": "TVING",
    "TV Land": "TVL",
    "UFC": "UFC",
    "UKTV": "UKTV",
    "Univision": "UNIV",
    "USA Network": "USAN",
    "Velocity": "VLCT",
    "VH1": "VH1",
    "Viceland": "VICE",
    "Viki": "VIKI",
    "Vimeo": "VMEO",
    "VRV": "VRV",
    "WatchMe": "WME",
    "W Network": "WNET",
    "WWE Network": "WWEN",
    "Xbox Video": "XBOX",
    "Yahoo": "YHOO",
    "YouTube Red": "RED",
    "ZDF": "ZDF",
}

# Disc regions
DISC_REGIONS = {
    "AFG": "AFG",
    "ALA": "ALA",
    "ALB": "CEE",
    "ALG": "ALG",
    "ASA": "ASA",
    "AND": "AND",
    "ANG": "ANG",
    "AIA": "AIA",
    "ATA": "ATA",
    "ATG": "ATG",
    "ARG": "ARG",
    "ARM": "ARM",
    "ARU": "ARU",
    "AUS": "AUS",
    "AUT": "AUT",
    "AZE": "AZE",
    "BAH": "BAH",
    "BHR": "BHR",
    "BAN": "BAN",
    "BRB": "BRB",
    "BLR": "BLR",
    "BEL": "BEL",
    "BLZ": "BLZ",
    "BEN": "BEN",
    "BER": "BER",
    "BHU": "BHU",
    "BOL": "BOL",
    "BES": "BES",
    "BIH": "BIH",
    "BOT": "BOT",
    "BVT": "BVT",
    "BRA": "BRA",
    "IOT": "IOT",
    "VGB": "VGB",
    "BRU": "BRU",
    "BUL": "CEE",
    "BFA": "BFA",
    "BDI": "BDI",
    "CAM": "CAM",
    "CMR": "CMR",
    "CAN": "CAN",
    "CPV": "CPV",
    "CAY": "CAY",
    "CTA": "CTA",
    "CHA": "CHA",
    "CHI": "CHI",
    "CHL": "CHI",
    "CHN": "CHN",
    "CXR": "CXR",
    "CCK": "CCK",
    "COL": "COL",
    "COM": "COM",
    "COD": "COD",
    "CGO": "CGO",
    "COK": "COK",
    "CRC": "CRC",
    "CIV": "CIV",
    "CRO": "CRO",
    "HRV": "CRO",
    "CUB": "CUB",
    "CUW": "CUW",
    "CYP": "CYP",
    "CZE": "CZE",
    "DEN": "NOR",
    "DNK": "NOR",
    "DJI": "DJI",
    "DMA": "DMA",
    "DOM": "DOM",
    "ECU": "ECU",
    "EGY": "EGY",
    "SLV": "SLV",
    "ESA": "SLV",
    "ENG": "ENG",
    "EQG": "EQG",
    "GEQ": "EQG",
    "GNQ": "EQG",
    "ERI": "ERI",
    "EST": "CEE",
    "SWZ": "SWZ",
    "ETH": "ETH",
    "FLK": "FLK",
    "FRO": "FRO",
    "FIJ": "FIJ",
    "FIN": "NOR",
    "FRA": "FRA",
    "GUF": "GUF",
    "TAH": "TAH",
    "PYF": "TAH",
    "ATF": "ATF",
    "GAB": "GAB",
    "GAM": "GAM",
    "GMB": "GAM",
    "GEO": "GEO",
    "GER": "GER",
    "DEU": "GER",
    "GHA": "GHA",
    "GIB": "GIB",
    "GRE": "GRE",
    "GRC": "GRE",
    "GRL": "GRL",
    "GRN": "GRN",
    "GRD": "GRN",
    "GLP": "GLP",
    "GUM": "GUM",
    "GUA": "GUA",
    "GTM": "GUA",
    "GGY": "GGY",
    "GUI": "GUI",
    "GIN": "GUI",
    "GNB": "GNB",
    "GBS": "GNB",
    "GUY": "GUY",
    "HAI": "HAI",
    "HTI": "HAI",
    "HMD": "HMD",
    "HON": "HON",
    "HND": "HON",
    "HKG": "HKG",
    "HUN": "HUN",
    "ISL": "ISL",
    "IND": "IND",
    "IDN": "IDN",
    "INA": "IDN",
    "IRN": "IRN",
    "IRI": "IRN",
    "IRQ": "IRQ",
    "IRL": "IRL",
    "IMN": "IMN",
    "ISR": "ISR",
    "ITA": "ITA",
    "JAM": "JAM",
    "JPN": "JPN",
    "JEY": "JEY",
    "JOR": "JOR",
    "KAZ": "KAZ",
    "KEN": "KEN",
    "KIR": "KIR",
    "PRK": "PRK",
    "KOR": "KOR",
    "KVX": "KVX",
    "KOS": "KVX",
    "KUW": "KUW",
    "KWT": "KUW",
    "KGZ": "KGZ",
    "LAO": "LAO",
    "LVA": "CEE",
    "LAT": "CEE",
    "LBN": "LBN",
    "LES": "LES",
    "LBR": "LBR",
    "LBY": "LBY",
    "LBA": "LBY",
    "LIE": "LIE",
    "LTU": "CEE",
    "LUX": "LUX",
    "MAC": "MAC",
    "MAD": "MAD",
    "MDG": "MAD",
    "MWI": "MWI",
    "MAW": "MWI",
    "MAS": "MAS",
    "MYS": "MAS",
    "MDV": "MDV",
    "MLI": "MLI",
    "MLT": "MLT",
    "MHL": "MHL",
    "MTQ": "MTQ",
    "MTN": "MTN",
    "MRT": "MTN",
    "MRI": "MRI",
    "MUS": "MRI",
    "MYT": "MYT",
    "MEX": "MEX",
    "FSM": "FSM",
    "MDA": "MDA",
    "MON": "MON",
    "MCO": "MON",
    "MNG": "MNG",
    "MGL": "MNG",
    "MSR": "MSR",
    "MAR": "MAR",
    "MOZ": "MOZ",
    "MYA": "MYA",
    "MMR": "MYA",
    "NAM": "NAM",
    "NRU": "NRU",
    "NEP": "NEP",
    "NPL": "NEP",
    "NED": "NLD",
    "NCL": "NCL",
    "NZL": "NZL",
    "NCA": "NCA",
    "NIC": "NCA",
    "NIG": "NIG",
    "NER": "NIG",
    "NIU": "NIU",
    "NFK": "NFK",
    "NIR": "NIR",
    "MNP": "MNP",
    "MKD": "MKD",
    "NOR": "NOR",
    "OMA": "OMA",
    "PAK": "PAK",
    "PLW": "PLW",
    "PLE": "PLE",
    "PSE": "PLE",
    "PAN": "PAN",
    "PNG": "PNG",
    "PAR": "PAR",
    "PRY": "PAR",
    "PER": "PER",
    "PHI": "PHI",
    "PHL": "PHI",
    "PCN": "PCN",
    "POL": "POL",
    "POR": "POR",
    "PRT": "POR",
    "PUR": "PUR",
    "PRI": "PUR",
    "QAT": "QAT",
    "REU": "REU",
    "ROU": "ROU",
    "RUS": "RUS",
    "RWA": "RWA",
    "BLM": "BLM",
    "SHN": "SHN",
    "SKN": "SKN",
    "SKN": "KNA",
    "LCA": "LCA",
    "MAF": "MAF",
    "SPM": "SPM",
    "VIN": "VIN",
    "VCT": "VIN",
    "SAM": "SAM",
    "WSM": "SAM",
    "SMR": "SMR",
    "STP": "STP",
    "KSA": "KSA",
    "SAU": "KSA",
    "SCO": "SCO",
    "SEN": "SEN",
    "SRB": "SRB",
    "SEY": "SEY",
    "SYC": "SEY",
    "SLE": "SLE",
    "SIN": "SIN",
    "SGP": "SIN",
    "SXM": "SXM",
    "SVK": "CEE",
    "SVN": "CEE",
    "SLO": "CEE",
    "SOL": "SOL",
    "SLB": "SOL",
    "SOM": "SOM",
    "RSA": "RSA",
    "ZAF": "RSA",
    "SGS": "SGS",
    "SSD": "SSD",
    "ESP": "ESP",
    "SPA": "ESP",
    "SRI": "SRI",
    "SRI": "LKA",
    "SDN": "SDN",
    "SUD": "SDN",
    "SUR": "SUR",
    "SJM": "SJM",
    "SWE": "NOR",
    "SUI": "SUI",
    "CHE": "SUI",
    "SYR": "SYR",
    "TPE": "TWN",
    "TWN": "TWN",
    "TJK": "TJK",
    "TAN": "TAN",
    "TZA": "TAN",
    "THA": "THA",
    "TLS": "TLS",
    "TOG": "TOG",
    "TKL": "TKL",
    "TGA": "TGA",
    "TON": "TGA",
    "TRI": "TRI",
    "TTO": "TRI",
    "TUN": "TUN",
    "TUR": "TUR",
    "TKM": "TKM",
    "TCA": "TCA",
    "TUV": "TUV",
    "UGA": "UGA",
    "UKR": "UKR",
    "UAE": "UAE",
    "ARE": "UAE",
    "GBR": "GBR",
    "UK": "GBR",
    "USA": "USA",
    "US": "USA",
    "UMI": "UMI",
    "VIR": "VIR",
    "ISV": "VIR",
    "URU": "URU",
    "URY": "URU",
    "UZB": "UZB",
    "VAN": "VAN",
    "VUT": "VAN",
    "VAT": "VAT",
    "VEN": "VEN",
    "VIE": "VIE",
    "VNM": "VIE",
    "WAL": "WAL",
    "WLF": "WLF",
    "ESH": "ESH",
    "YEM": "YEM",
    "ZAM": "ZAM",
    "ZMB": "ZAM",
    "ZIM": "ZIM",
    "ZWE": "ZIM",
    "CEE": "CEE",
    "BGR": "CEE",
    "FRE": "FRA",
}
